Improve CS.
Use "alpine:latest" insteadof "alpine:3.4".

Use "timonier/version-lister".

diff --git a/bin/installer b/bin/installer
--- a/bin/installer
+++ b/bin/installer
@@ -1,27 +1,31 @@
 #!/bin/sh
-set -x
+set -eux
+
+# Check environment
 
 fail() {
-    echo $1 1>&2
-    echo "Usage: $0 [install|uninstall]" 1>&2
+    echo "$1" 1>&2
+    echo "Usage: $(basename "$0") [install|uninstall]" 1>&2
     exit 1
 }
 
-if [ $# -lt 1 ] ; then
+if [ "$#" -lt 1 ] ; then
     fail "Invalid number of arguments."
 fi
 
-if [ $(id -u) -ne 0 ] ; then
+if [ "$(id --user)" -ne 0 ] ; then
     fail "Impossible to prepare the system without root privileges."
 fi
 
-if [ $(uname) != "Linux" ] ; then
+if [ "$(uname)" != "Linux" ] ; then
     fail "Impossible to prepare another operating system than Linux."
 fi
 
+# Run installer
+
 case $1 in
     install )
-        curl -sLo /usr/local/bin/drive "https://github.com/timonier/drive/raw/master/bin/drive"
+        curl --location --output /usr/local/bin/drive "https://github.com/timonier/drive/raw/master/bin/drive"
         chmod +x /usr/local/bin/drive
     ;;
 
@@ -30,5 +34,5 @@ case $1 in
     ;;
 
     * )
-        fail "Argument $1 is invalid."
+        fail "Argument \"$1\" is invalid."
 esac
